name: dartlang_project_templates
# If intended for publishing, replace `publish_to: none` with `version: 0.0.1`
publish_to: none
description: A sample library.
repository: https://github.com/dart-lang/dartlang_project_templates

environment:
  sdk: ^3.0.0

dependencies:
  # lib_name: ^1.2.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.16.0
