name: dartlang_project_templates
version: 0.1.0
description: A sample library.
repository: https://github.com/dart-lang/dartlang_project_templates

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # lib_name: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
