name: sample
version: 0.1.0-dev
description: A sample library.
author: Foo Bar <foobar@example.com>
homepage: https://github.com/google/sample

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  # lib_name: "^1.2.0"

dev_dependencies:
  # Narrow this constraint if you use more advanced test features.
  test: "^0.12.0"
