language: dart

# Speed up builds by using containerization. Disable this if you need to use
# sudo in your scripts.
sudo: false

dart:
- dev
- stable

# See https://docs.travis-ci.com/user/languages/dart/ for details.
dart_task:
- test: --platform vm
# Uncomment this line to run tests on the browser.
# - test: --platform firefox

# Only run one instance of the formatter and the analyzer, rather than running
# them against each Dart version.
matrix:
  include:
  - dart: stable
    dart_task: dartfmt
  - dart: dev
    dart_task: dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
