name: sample
version: 0.0.1
description: A sample library.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/sample

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any
dev_dependencies:
# change this to a specific version range when you create your project
  test: any
