name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # These are the latest versions of the github actions; dependabot will
      # send PRs to keep these up-to-date.
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d

      - name: Install dependencies
        run: dart pub get
  
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
